# Generated by Django 3.1.1 on 2020-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
