# Generated by Django 3.1.1 on 2020-09-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_user_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='content',
        ),
    ]
